DROP DATABASE IF EXISTS EMPLOYEE_TRACKER_DB;

CREATE DATABASE EMPLOYEE_TRACKER_DB;

USE EMPLOYEE_TRACKER_DB;

CREATE TABLE DEPARTMENTS (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    DEPARTMENT_NAME  VARCHAR(30) UNIQUE,
    PRIMARY KEY(ID)
);

CREATE TABLE ROLES (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(30) UNIQUE ,
    SALARY DECIMAL,
    DEPARTMENT_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
);


CREATE TABLE EMPLOYEES (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    ROLES_ID INTEGER,
    MANAGER_ID INTEGER NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ROLES_ID) REFERENCES ROLES(ID),
    FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES(ID)
);

